[workspace]

members = [
    "_playground",
    "t2_1_layout",
    "t2_2_new",
    "t2_3_ownership_101",
    "t2_4_push",
    "t2_5_pop",
    "t2_6_testing",
    "t2_7_drop",
    "t2_8_final_code",
    "t3_1_option",
    "t3_2_generic",
    "t3_3_peek",
    "t3_4_into_iter",
    "t3_5_iter",
]
